-- ============================================================================
-- Gainditu · Seed de preguntas · Personal de Apoyo
-- TEST apoyo20 — T.20 Control de acceso, identificación, recepción, información
--                y atención en dependencias administrativas
-- 30 preguntas · formato tabla public.preguntas
--   columnas: id (uuid), test_id, orden, enunciado, opciones (jsonb[4]),
--             correcta (int 0-index), explicacion, created_at (default)
-- Nivel/estilo: distractores plausibles + explicación que desmonta cada opción,
--   con apoyo normativo donde aplica (LOPDGDD art. 22, Ley 31/1995 PRL,
--   RD 393/2007 autoprotección, Ley 39/2015 atención a la ciudadanía).
-- Cómo ejecutar: pégalo en Supabase → SQL Editor → Run. Idempotente.
-- ============================================================================

begin;

delete from public.preguntas where test_id = 'apoyo20';

insert into public.preguntas (id, test_id, orden, enunciado, opciones, correcta, explicacion) values
(gen_random_uuid(), 'apoyo20', 1,
 'El control de acceso a las dependencias administrativas tiene como finalidad esencial:',
 '["Recaudar tasas por la entrada de visitantes.", "Garantizar la seguridad de las personas, los bienes y las instalaciones, ordenando y verificando entradas y salidas.", "Restringir el derecho de la ciudadanía a relacionarse con la Administración.", "Asumir las funciones de investigación propias de las Fuerzas y Cuerpos de Seguridad."]'::jsonb,
 1,
 'El control de acceso ordena y verifica las entradas y salidas para proteger a personas, bienes e instalaciones. No es recaudatorio (A). No puede restringir el derecho de acceso a los servicios públicos, que es un derecho de la ciudadanía (C). Y las labores de seguridad e investigación corresponden a las FCS o a la seguridad privada habilitada, no al personal de apoyo (D), que solo aplica los medios de control previstos.'),
(gen_random_uuid(), 'apoyo20', 2,
 'El registro de datos de visitantes (nombre, DNI, hora de entrada) constituye un tratamiento de datos personales, por lo que su régimen es el del:',
 '["Reglamento (UE) 2016/679 (RGPD) y la LOPDGDD, con finalidad determinada y acceso restringido.", "Código Civil, por tratarse de datos privados.", "Reglamento del centro exclusivamente, sin más límites.", "Estatuto de los Trabajadores."]'::jsonb,
 0,
 'Al recoger identidad y hora se tratan datos personales, sometidos al RGPD y a la LOPDGDD (LO 3/2018): finalidad determinada —la seguridad—, minimización, acceso restringido y conservación limitada. No es materia del Código Civil (B), ni queda al libre criterio del reglamento interno (C), ni del Estatuto de los Trabajadores (D), que regula la relación laboral, no el tratamiento de datos de terceros.'),
(gen_random_uuid(), 'apoyo20', 3,
 'La instalación de cámaras de videovigilancia en los accesos, conforme al art. 22 de la LOPDGDD, exige entre otros requisitos:',
 '["Grabar audio ambiental de forma permanente.", "Colocar un dispositivo informativo visible que advierta de la existencia de las cámaras y del responsable del tratamiento.", "Conservar las imágenes de forma indefinida.", "Difundir las grabaciones en la web del organismo."]'::jsonb,
 1,
 'El art. 22 LOPDGDD obliga a informar mediante un dispositivo (cartel) que indique la existencia de la videovigilancia y el responsable ante quien ejercer los derechos. Como regla, no se capta audio (A), las imágenes se suprimen en un plazo máximo (con carácter general un mes, salvo prueba de infracción) por lo que no cabe conservación indefinida (C), y difundirlas públicamente (D) vulneraría la protección de datos.'),
(gen_random_uuid(), 'apoyo20', 4,
 'La exigencia de identificación mediante documento (DNI, pasaporte) a quien accede a una dependencia debe graduarse:',
 '["Siempre, incluso en las zonas de atención al público de libre acceso.", "Nunca, porque vulnera la intimidad.", "Según el nivel de seguridad de la dependencia y la zona a la que se pretende acceder.", "Solo si el visitante viste de manera formal."]'::jsonb,
 2,
 'El control se aplica de forma proporcionada: en las áreas de libre acceso al público no suele requerirse identificación, mientras que en zonas internas o de seguridad reforzada sí. Por eso ni "siempre" (A) —desproporcionado en zonas públicas—, ni "nunca" (B) —dejaría sin control las zonas sensibles—, ni criterios subjetivos como la vestimenta (D), que serían discriminatorios.'),
(gen_random_uuid(), 'apoyo20', 5,
 'La acreditación o tarjeta de visitante entregada en recepción debe:',
 '["Conservarla el visitante como justificante de su visita.", "Portarse en lugar visible durante la estancia y devolverse a la salida.", "Entregarse únicamente a cargos y autoridades.", "Sustituir al documento de identidad del visitante."]'::jsonb,
 1,
 'La acreditación identifica al visitante y su autorización mientras permanece en el edificio, por lo que se lleva visible y se devuelve al salir para su control y reutilización. No es un justificante que el visitante conserve (A), no se reserva a autoridades (B se descarta por ese motivo en C) ni sustituye al documento de identidad (D): son cosas distintas.'),
(gen_random_uuid(), 'apoyo20', 6,
 'Si una persona pretende acceder a una zona restringida careciendo de autorización, la actuación correcta del personal de control es:',
 '["Permitir el paso si la persona insiste o alega urgencia.", "Acompañarla personalmente a la zona restringida para agilizar.", "Denegar el acceso con cortesía y derivar a la unidad responsable o a seguridad según el protocolo.", "Retenerla e identificarla mediante un registro corporal."]'::jsonb,
 2,
 'Sin autorización no se accede a zonas restringidas: se deniega con corrección y se deriva a quien corresponda. Ceder ante la insistencia (A) o franquear el paso (B) rompe el control. Y el registro corporal o la retención (D) exceden las competencias del personal de apoyo, propias de las FCS.'),
(gen_random_uuid(), 'apoyo20', 7,
 'Ante una persona con discapacidad visual que llega a recepción, la atención accesible consiste en:',
 '["Dirigir la comunicación a su acompañante en lugar de a ella.", "Entregarle un plano impreso del edificio.", "Presentarse verbalmente, ofrecer ayuda y describir la orientación o el recorrido, o acompañarla si lo desea.", "Elevar notablemente el tono de voz."]'::jsonb,
 2,
 'La comunicación se dirige a la propia persona, identificándose de palabra y ofreciendo guía verbal o acompañamiento. Hablar solo con el acompañante (A) la invisibiliza, un plano visual (B) no es accesible para ella, y gritar (D) confunde discapacidad visual con auditiva: no procede.'),
(gen_random_uuid(), 'apoyo20', 8,
 'Cuando el personal de recepción desconoce la respuesta a una consulta de la ciudadanía, lo correcto es:',
 '["Facilitar una respuesta aproximada para no dejar sin contestar.", "Orientar hacia la unidad o el servicio competente, o indicar dónde obtener la información.", "Indicar que ese asunto no forma parte de sus funciones.", "Pedir a la persona que formule la consulta por escrito otro día."]'::jsonb,
 1,
 'El deber de facilitar el ejercicio de los derechos (art. 13 Ley 39/2015) obliga a orientar hacia el servicio competente o la fuente adecuada. Improvisar datos (A) puede inducir a error, desentenderse (C) incumple el deber de asistencia y aplazar sin causa (D) entorpece el servicio.'),
(gen_random_uuid(), 'apoyo20', 9,
 'En un aviso de evacuación, y conforme al plan de autoprotección (RD 393/2007), el personal de control de acceso debe:',
 '["Cerrar todas las salidas para evitar aglomeraciones.", "Permanecer en su puesto sin intervenir.", "Facilitar la salida ordenada por las vías previstas y colaborar en el recuento y con los equipos de emergencia.", "Impedir la salida hasta recibir una segunda confirmación."]'::jsonb,
 2,
 'Según el plan de autoprotección, el control de acceso ayuda a una evacuación ordenada por las vías y salidas previstas y colabora en el recuento y con los equipos de intervención. Cerrar salidas (A) o retener a las personas (D) crearía un riesgo grave, y quedarse pasivo (B) incumple las funciones asignadas en el plan.'),
(gen_random_uuid(), 'apoyo20', 10,
 'Respecto de los objetos y equipajes que porta un visitante, el personal de control de acceso:',
 '["Puede efectuar registros corporales cuando lo estime oportuno.", "Debe requisar todos los bolsos y mochilas en cualquier caso.", "Aplica únicamente los medios de control previstos (arco detector, escáner de bandeja) conforme al protocolo, sin practicar registros personales.", "No puede pedir nunca que se muestre el contenido de una bolsa."]'::jsonb,
 2,
 'El personal de apoyo aplica los medios técnicos previstos (arcos, escáneres) dentro de sus competencias y del protocolo del centro. Los registros corporales (A) y las requisas (B) corresponden a las FCS. Y afirmar que "nunca" puede pedir mostrar el contenido (D) es excesivo: dentro del protocolo de control sí puede solicitarlo de forma proporcionada.'),
(gen_random_uuid(), 'apoyo20', 11,
 'La atención de una llamada en la centralita o recepción debe iniciarse:',
 '["Dejando que suene varias veces para filtrar llamadas.", "Con prontitud, identificando el organismo o centro y ofreciendo ayuda.", "Solicitando en primer lugar el nombre y el DNI de quien llama.", "Poniendo música de espera hasta que la persona insista."]'::jsonb,
 1,
 'La llamada se atiende sin demora, identificando el centro y ofreciendo ayuda, como parte de una atención de calidad. Demorar a propósito (A) o abrir con música de espera (D) deteriora el servicio, y exigir datos personales de entrada (C) no es proporcionado ni necesario para orientar.'),
(gen_random_uuid(), 'apoyo20', 12,
 'Ante una persona visiblemente alterada que eleva el tono en el mostrador, la pauta recomendada es:',
 '["Responder con el mismo tono para marcar autoridad.", "Darle la espalda hasta que se calme.", "Mantener la calma, practicar escucha activa y reconducir la conversación con serenidad y empatía.", "Advertirle de inmediato de que se avisará a la policía."]'::jsonb,
 2,
 'La técnica adecuada de gestión de situaciones tensas es mantener la calma, escuchar y reconducir con serenidad. Igualar el tono (A) escala el conflicto, ignorar (B) lo agrava, y amenazar de entrada con la policía (D) es desproporcionado; el aviso a seguridad se reserva para cuando exista un riesgo real.'),
(gen_random_uuid(), 'apoyo20', 13,
 'El principio de igualdad en la atención al público implica que:',
 '["Se atiende antes a las personas conocidas por el personal.", "Se atiende a todas las personas sin discriminación, por orden o cita y con criterios objetivos, salvo las preferencias legalmente establecidas.", "Se prioriza según la apariencia o el motivo de la visita.", "El personal elige libremente a quién atiende primero."]'::jsonb,
 1,
 'La atención se presta sin discriminación, respetando el turno o la cita y los criterios objetivos, con las preferencias fijadas por la norma. Los favoritismos por conocimiento (A), apariencia (C) o criterio personal (D) vulneran la igualdad de trato.'),
(gen_random_uuid(), 'apoyo20', 14,
 'La confidencialidad en el mostrador de recepción exige que la información con datos personales de terceros:',
 '["Se comente en voz alta para agilizar.", "Se proteja de la vista y el oído de otras personas presentes.", "Se comparta con quien lo solicite educadamente.", "Se exhiba en el mostrador para que cada visitante localice su expediente."]'::jsonb,
 1,
 'Los datos personales manejados en recepción deben quedar a salvo de miradas y oídos ajenos (deber de confidencialidad y seguridad del RGPD). Comentarlos en voz alta (A), cederlos a cualquiera (C) o exhibirlos (D) supondría una comunicación no autorizada de datos.'),
(gen_random_uuid(), 'apoyo20', 15,
 'Cuando llega un visitante con cita previa concertada con una unidad, el procedimiento habitual de recepción es:',
 '["Denegar el acceso por seguridad.", "Verificar la cita, registrar la entrada, entregar acreditación si procede y avisar a la unidad de destino.", "Dirigirlo a la unidad sin registrar la visita ni avisar.", "Pedirle que gestione él mismo su acceso a la planta."]'::jsonb,
 1,
 'Con cita previa se comprueba la reserva, se registra la entrada, se acredita cuando corresponde y se comunica la llegada a la unidad. Denegar el acceso a una visita citada (A), no dejar constancia ni coordinar (C) o desentenderse de su itinerario (D) serían incorrectos.'),
(gen_random_uuid(), 'apoyo20', 16,
 'Frente a un envío o paquete sospechoso recibido en el acceso, la actuación correcta es:',
 '["Abrirlo con cuidado para comprobar su contenido.", "No manipularlo, aislar la zona y avisar a seguridad siguiendo el protocolo.", "Guardarlo en un cajón hasta que lo reclamen.", "Devolverlo al mensajero sin darle importancia."]'::jsonb,
 1,
 'Ante un envío sospechoso no se manipula ni se abre: se aísla la zona y se activa el aviso a seguridad según el protocolo. Abrirlo (A) o guardarlo (C) podría entrañar un riesgo, y devolverlo sin más (D) traslada el peligro sin gestionarlo.'),
(gen_random_uuid(), 'apoyo20', 17,
 'Si una consulta presentada en recepción corresponde a la competencia de otra Administración, la buena práctica es:',
 '["Comunicar que no es asunto del organismo y despedir a la persona.", "Tramitar uno mismo la solicitud aunque no se sea competente.", "Orientar sobre el organismo competente y, en lo posible, facilitar datos de contacto.", "Archivar la consulta sin dar respuesta."]'::jsonb,
 2,
 'Aunque el asunto sea de otra Administración, el deber de asistencia lleva a orientar hacia el organismo competente y facilitar cómo contactar. Desentenderse (A) o no responder (D) incumple ese deber, y tramitar sin competencia (B) generaría un acto viciado.'),
(gen_random_uuid(), 'apoyo20', 18,
 'El parte o libro de incidencias del servicio de control de acceso tiene por objeto:',
 '["Registrar asuntos personales del personal de turno.", "Dejar constancia de hechos relevantes, anomalías o incidencias del turno y trasladarlos al siguiente.", "Anotar avisos de carácter publicitario.", "Sustituir al registro de visitas."]'::jsonb,
 1,
 'En el parte de incidencias se recogen los hechos relevantes o anomalías del turno (accesos no autorizados, averías, emergencias) para su seguimiento y traspaso al relevo. No es un cuaderno personal (A), ni publicitario (C), ni sustituye al registro de visitas (D), que cumple otra función.'),
(gen_random_uuid(), 'apoyo20', 19,
 'Sobre la información que el personal de control puede facilitar respecto de expedientes o asuntos internos:',
 '["Puede informar del contenido de cualquier expediente que conozca.", "Facilita únicamente información de carácter general y deriva las consultas concretas a la unidad competente, preservando la confidencialidad.", "Debe comentar los expedientes cuando se lo pidan con amabilidad.", "Puede confirmar datos de terceros si la persona dice ser familiar."]'::jsonb,
 1,
 'El personal de recepción ofrece información general y orienta; las cuestiones concretas de un expediente las resuelve la unidad competente, respetando la confidencialidad y la protección de datos. Difundir contenidos (A), comentarlos por cortesía (C) o confirmar datos de terceros por un vínculo alegado (D) supondría una cesión indebida.'),
(gen_random_uuid(), 'apoyo20', 20,
 'Una señalización adecuada en el acceso de un edificio administrativo contribuye a:',
 '["Aumentar el número de consultas en recepción.", "Orientar a la ciudadanía, reducir consultas repetitivas y ordenar el flujo de personas.", "Sustituir por completo al personal de recepción.", "Dificultar el tránsito por motivos de seguridad."]'::jsonb,
 1,
 'La señalización clara guía hacia el destino, disminuye las consultas repetidas y ordena el tránsito, complementando —no sustituyendo— la atención personal (C). No busca aumentar consultas (A) ni entorpecer el paso (D), sino facilitarlo.'),
(gen_random_uuid(), 'apoyo20', 21,
 'La atención preferente a determinadas personas (mayores, embarazadas, personas con discapacidad) en el mostrador:',
 '["No existe: rige siempre el orden estricto de llegada.", "Se aplica cuando así está establecido, compatibilizándola con el buen orden general de la atención.", "Depende del criterio del personal de cada día.", "Se reserva a autoridades y cargos públicos."]'::jsonb,
 1,
 'Existen supuestos de atención preferente para ciertos colectivos cuando la norma o las instrucciones del centro lo prevén, sin desorganizar la atención al resto. No es que rija siempre el orden estricto (A), ni depende del criterio subjetivo (C), ni se reserva a cargos (D).'),
(gen_random_uuid(), 'apoyo20', 22,
 'Si una persona solicita acceder fuera del horario de atención al público, lo correcto es:',
 '["Permitir el acceso en todo caso.", "Informar del horario y, si existe un cauce para ello, gestionar la excepción conforme a las normas del centro.", "Negar el acceso sin ofrecer ninguna explicación.", "Acompañarla al interior aunque las dependencias estén cerradas."]'::jsonb,
 1,
 'Se informa con claridad del horario y, si hay un procedimiento para visitas autorizadas o citas especiales, se gestiona según las normas del centro. Ni acceso indiscriminado (A y D), que compromete la seguridad, ni una negativa sin explicación (C), contraria a la buena atención.'),
(gen_random_uuid(), 'apoyo20', 23,
 'Ante una emergencia médica de un visitante en el vestíbulo, la primera actuación del personal de control es:',
 '["Continuar con las tareas habituales y esperar a que se recupere.", "Trasladarlo de inmediato al exterior del edificio.", "Avisar a los servicios de emergencia o de primeros auxilios y no mover a la persona salvo peligro inminente.", "Buscar a un familiar antes de emprender cualquier acción."]'::jsonb,
 2,
 'Se activa el aviso a emergencias (112) o al servicio de primeros auxilios del centro y se evita mover a la persona salvo riesgo inminente, para no agravar posibles lesiones. Ignorar (A), trasladar sin criterio (B) o demorar la ayuda buscando a un familiar (D) empeoraría la situación.'),
(gen_random_uuid(), 'apoyo20', 24,
 'La comunicación no verbal del personal de recepción (postura, contacto visual, sonrisa):',
 '["Es irrelevante frente a lo que se dice.", "Influye en la percepción de la ciudadanía y refuerza una atención cercana y profesional.", "Solo tiene efecto en la atención telefónica.", "Debe evitarse para mantener la distancia."]'::jsonb,
 1,
 'El lenguaje corporal transmite disponibilidad y respeto e influye en cómo percibe la persona el servicio; una postura abierta, el contacto visual y la sonrisa refuerzan la calidad de la atención presencial. Por eso no es irrelevante (A), no se limita al teléfono (C) —donde precisamente no se ve— ni conviene suprimirlo (D).'),
(gen_random_uuid(), 'apoyo20', 25,
 'Un sistema de control de accesos con torniquetes y tarjeta identificativa aporta principalmente:',
 '["Un elemento decorativo para el vestíbulo.", "La automatización y el registro de los accesos autorizados, agilizando el control.", "La eliminación de toda necesidad de recepción y señalización.", "La sustitución del plan de autoprotección."]'::jsonb,
 1,
 'Los torniquetes con lector de tarjeta permiten controlar y registrar de forma automática los accesos autorizados, agilizando el flujo. No son decoración (A), no eliminan la atención personal ni la señalización (C) y nada tienen que ver con sustituir el plan de autoprotección (D).'),
(gen_random_uuid(), 'apoyo20', 26,
 'Los registros de acceso que contienen datos personales deben conservarse:',
 '["De forma indefinida y accesibles a cualquier persona.", "Durante el plazo previsto en la normativa o instrucciones, con medidas de seguridad y acceso restringido.", "Un único día, destruyéndolos siempre al cierre.", "En el domicilio particular del personal de turno."]'::jsonb,
 1,
 'Conforme al principio de limitación del plazo de conservación (RGPD), los registros se guardan el tiempo previsto, con medidas de seguridad y acceso restringido. No cabe conservación indefinida y pública (A), ni una destrucción diaria automática (C) que impediría trazar incidencias, ni la custodia fuera del centro (D).'),
(gen_random_uuid(), 'apoyo20', 27,
 'La coordinación entre el servicio de recepción y las unidades del edificio resulta importante porque:',
 '["Permite controlar el rendimiento del personal.", "Facilita anunciar visitas, encajar citas y responder con agilidad a la ciudadanía.", "Sirve para distribuir publicidad interna.", "Evita tener que registrar las visitas."]'::jsonb,
 1,
 'Una buena coordinación permite avisar de las visitas, gestionar las citas y ofrecer respuestas rápidas, mejorando el servicio. No tiene finalidad de control del personal (A), ni publicitaria (C), ni exime del registro de visitas (D), que sigue siendo necesario.'),
(gen_random_uuid(), 'apoyo20', 28,
 'La primera actuación adecuada al recibir a un visitante en el mostrador es:',
 '["Solicitar directamente su DNI antes de cualquier otra cosa.", "Saludar, identificar el servicio y preguntar en qué se le puede ayudar.", "Pedirle que espere sin dirigirle la palabra.", "Avisar a seguridad de forma preventiva."]'::jsonb,
 1,
 'La atención comienza con un saludo cortés y el ofrecimiento de ayuda para orientar la visita. Pedir el documento (A) procede cuando el acceso lo requiere, no como primer gesto; hacer esperar sin atender (C) o alarmar a seguridad sin motivo (D) no corresponden a una buena recepción.'),
(gen_random_uuid(), 'apoyo20', 29,
 'La atención presencial de calidad en recepción se caracteriza por:',
 '["Un trato distante y respuestas cortantes para ganar tiempo.", "Amabilidad, escucha activa, lenguaje claro y disposición a ayudar, con trato igual a todas las personas.", "El uso de tecnicismos que demuestren dominio de la materia.", "Priorizar a las personas que el personal conoce."]'::jsonb,
 1,
 'La calidad en la atención presencial implica amabilidad, escucha, claridad y voluntad de ayudar, tratando a todas las personas por igual. El trato distante (A), los tecnicismos innecesarios (C) —que dificultan la comprensión— y los favoritismos (D) son contrarios a ese objetivo.'),
(gen_random_uuid(), 'apoyo20', 30,
 'El personal de control de acceso, en relación con las Fuerzas y Cuerpos de Seguridad, tiene una función:',
 '["Sustitutiva: asume sus competencias dentro del edificio.", "De apoyo y colaboración: aplica los controles previstos y avisa o auxilia a las FCS o a la seguridad privada cuando el protocolo lo requiere.", "Independiente: puede practicar detenciones e identificaciones coactivas.", "Inexistente: no interviene ante ninguna incidencia de seguridad."]'::jsonb,
 1,
 'La función del personal de apoyo es de colaboración: aplica los medios de control previstos y avisa o auxilia a las FCS o a la seguridad privada habilitada cuando corresponde. No sustituye sus competencias (A), no puede practicar detenciones ni identificaciones coactivas (C) —reservadas a la autoridad— pero tampoco es ajeno a la seguridad del centro (D).');

commit;

-- Verificación: select count(*) from public.preguntas where test_id = 'apoyo20';  -- 30
